version: "3.9"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5438:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  test_db:
    container_name: test_postgresql_db
    image: postgres
    restart: always
    ports:
      - 5439:5433
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}


  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head && uvicorn todo.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always